# Alt Küme Üzerinde İşlem Yapmak

In [2]:
import numpy as np


In [3]:
a = np.random.randint( 10 , size= (5,5) )

In [4]:
a

array([[4, 2, 5, 0, 7],
       [2, 1, 7, 5, 9],
       [5, 0, 1, 4, 3],
       [3, 3, 4, 7, 2],
       [0, 3, 4, 2, 7]])

In [5]:
alt=a[0:3 , 0:2]

In [6]:
alt


array([[4, 2],
       [2, 1],
       [5, 0]])

In [7]:
alt[0,0] #--> Burada ilk indexlerdeki değeri bulduk.

4

In [9]:
alt[0,0]=999

In [14]:
alt[1,1]=777

In [15]:
a

array([[999,   2,   5,   0,   7],
       [  2, 777,   7,   5,   9],
       [  5,   0,   1,   4,   3],
       [  3,   3,   4,   7,   2],
       [  0,   3,   4,   2,   7]])

In [16]:
#Burada alt kümeyi değiştirirken ana matrisi değiştiriyoruz.

Değiştirmemek için copy fonksiyonunu kullanıyoruz.


In [20]:
v=np.random.randint(8, size= (4,4))

In [21]:
v

array([[5, 6, 4, 3],
       [4, 1, 4, 7],
       [7, 4, 3, 2],
       [3, 1, 2, 5]])

In [23]:
alt=v[0:2, 0:1].copy()

In [24]:
alt

array([[5],
       [4]])

In [25]:
alt[0,0]=555

In [26]:
alt

array([[555],
       [  4]])

In [27]:
v

array([[5, 6, 4, 3],
       [4, 1, 4, 7],
       [7, 4, 3, 2],
       [3, 1, 2, 5]])

Görüldüğü üzere copy fonksiyonunu kullandığımız için ana matris üzerinde değişiklik olmamıştır.