# Array birleştirme( Concatenation)

In [2]:
import numpy as np


In [3]:
x=np.array([3,4,5])
y=np.array([7,8,9])


In [4]:
np.concatenate([x,y])

array([3, 4, 5, 7, 8, 9])

İki array birleştirme yapıldı.

In [5]:
z=np.array([10,11,12])

In [6]:
np.concatenate([x,y,z])

array([ 3,  4,  5,  7,  8,  9, 10, 11, 12])

## İki boyutlu arrayler için birleştirme

In [8]:
a=np.array([[1,2,3],
          [7,8,9]])

In [9]:
# Kendimiz iki boyutlu bir matris oluşturduk.

array([[1, 2, 3],
       [7, 8, 9]])

In [10]:
np.concatenate([a,a])

array([[1, 2, 3],
       [7, 8, 9],
       [1, 2, 3],
       [7, 8, 9]])

Yukarıda da gözüktüğü üzere iki matrisi birleştirme işlemi yaptık.

In [11]:
np.concatenate([a,a], axis=0) #Sütunlara göre birleştirme yapar.

array([[1, 2, 3],
       [7, 8, 9],
       [1, 2, 3],
       [7, 8, 9]])

In [12]:
np.concatenate([a,a], axis=1) #Satırlara göre birleştirme yapılmıştır.

array([[1, 2, 3, 1, 2, 3],
       [7, 8, 9, 7, 8, 9]])