# Array ayırma ( Spilitting)

In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,5,6,7,8,9])


In [4]:
np.split(x,(3,5))

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]

Burada indekse göre sayııp ayrılır. Dikkat edilmesi gereken önemli bir husustur.

Ekstra olarak otomatik olarak şöyle atama yapabiliriz.


In [5]:
a,b,c=np.split(x,(3,5))

In [6]:
a


array([1, 2, 3])

In [7]:
b

array([4, 5])

In [8]:
c

array([6, 7, 8, 9])

# İki boyutlu ayırma

In [9]:
m=np.arange(16).reshape(4,4)

In [10]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.vsplit(m,[2]) # Dikey olarak 2 nciden sonra ayırır.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [12]:
ust, alt = np.vsplit(m,[2])

In [13]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Bu şekilde ayırma yapabiliriz.


In [16]:
np.hsplit(m,[2]) # Dikey olarak ayırma bu şekilde yapılabilir.

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]