 # Array Sıralama (Sorting)

In [1]:
import numpy as np


In [2]:
v = np.array ([86,12,56,6,5,9])

In [3]:
v

array([86, 12, 56,  6,  5,  9])

In [4]:
np.sort(v) # Sıralama bu şekilde yapılır

array([ 5,  6,  9, 12, 56, 86])

In [5]:
#İki boyutlu sıralama 


In [6]:
m=np.random.normal(30,6,(4,4)) 30= ortalama 6= standart sapma

In [7]:
m

array([[27.59060254, 30.51277281, 35.82063677, 29.53528336],
       [31.09828821, 25.49327128, 26.71923341, 32.96692627],
       [21.94730734, 25.42666786, 29.34480355, 32.24658785],
       [28.36192614, 27.66556615, 38.58256876, 31.33596202]])

In [8]:
np.sort(m , axis=1) # Satırlara göre sıralıyoruz.

array([[27.59060254, 29.53528336, 30.51277281, 35.82063677],
       [25.49327128, 26.71923341, 31.09828821, 32.96692627],
       [21.94730734, 25.42666786, 29.34480355, 32.24658785],
       [27.66556615, 28.36192614, 31.33596202, 38.58256876]])

In [9]:
np.sort(m , axis=0) # Sütunlara göre sıralıyoruz.

array([[21.94730734, 25.42666786, 26.71923341, 29.53528336],
       [27.59060254, 25.49327128, 29.34480355, 31.33596202],
       [28.36192614, 27.66556615, 35.82063677, 32.24658785],
       [31.09828821, 30.51277281, 38.58256876, 32.96692627]])