# FANCY INDEX KULLANIMI

In [2]:
import numpy as np

In [3]:
v=np.arange(0,40,3)

In [4]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [5]:
v[1]

3

In [6]:
v[5]

15

Bu şekilde çağırabiliyorduk.Yada liste şeklinde çağırırsak.

In [8]:
[v[1],v[5],v[7]] # Bu şekilde de çağırabiliyoruz.

[3, 15, 21]

In [9]:
getir=[1,5,7]

In [12]:
v[getir] #Fancy özelliğini kullanrak kısaca böyle getirebiliriz.Teker teker yazmaya gerek kalmayacaktır.

array([ 3, 15, 21])

## İki boyutlu Fancy kullanımı

In [14]:
x=np.arange(9).reshape((3,3))

In [15]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
satır=np.array([0,1])
sutun=np.array([1,2])

In [19]:
x[satır,sutun]

array([1, 5])

In [20]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])