# Slicing ile Elemanlara Erişmek ( Array alt kümesine erişmek )

In [1]:
import numpy as np


In [2]:
a=np.arange(20,30) # arange fonksiyonu belli bir aralığı almak için kullanılır.

In [3]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
a[0:3] #Burada sıfırıncı index dahil ediyoruz. Ama üçüncü index dahil etmiyoruz.

array([20, 21, 22])

In [7]:
a[3:] # Üçüncü indexi alıp geri kalanı belirtmediğimiz için hepsini alıyor.

array([23, 24, 25, 26, 27, 28, 29])

In [8]:
a[1 :: 2] #Birinci indexi al ikişer ikişer arttır.

array([21, 23, 25, 27, 29])

In [10]:
a[0::2] #İkişer ikişer arttır.Başlangıçta sıfırıncı index alındı.

array([20, 22, 24, 26, 28])

In [11]:
a[0::3]

array([20, 23, 26, 29])

**Slicing işlemi dilimlemek anlamında kullanılır , parçalayarak bu alt parçalara ayırırız.**

#İki boyutlu slice işlemleri  

In [12]:
m=np.random.randint(10 , size=(5,5))

In [13]:
m

array([[7, 4, 1, 6, 0],
       [8, 2, 8, 3, 9],
       [3, 4, 7, 6, 4],
       [2, 6, 9, 3, 7],
       [2, 4, 2, 6, 9]])

In [14]:
m[:,0]

array([7, 8, 3, 2, 2])

Burada bütün satırlar alınır sıfırıncı index (sütunlarda) alınır.

In [16]:
m[:,1]

array([4, 2, 4, 6, 4])

In [18]:
m[1,:]

array([8, 2, 8, 3, 9])

Birinci satır alınıyor.Bütun sütunlar alınıyor.

In [20]:
m # Tekrar çağıralım.

array([[7, 4, 1, 6, 0],
       [8, 2, 8, 3, 9],
       [3, 4, 7, 6, 4],
       [2, 6, 9, 3, 7],
       [2, 4, 2, 6, 9]])

In [19]:
m[0:2, 0:3] # m[a,b] # --> a satırları , b sütunları ifade etmektedirler. 0 dan 2 e kadar(2 dahil değil)

array([[7, 4, 1],
       [8, 2, 8]])

In [21]:
m[1:3, 2:4] #Kesişilen bölgeye dikkat edilmelidir.

array([[8, 3],
       [7, 6]])