# Numpy arrayı oluşturma

In [2]:
import numpy as np 

In [3]:
np.array([2,3,4,5,6])


array([2, 3, 4, 5, 6])

In [10]:
a = np.array([2,3,4,5,6])

In [11]:
type (a)

numpy.ndarray

In [13]:
np.array([3.14 , 8 ,9, 10,4])

array([ 3.14,  8.  ,  9.  , 10.  ,  4.  ])

As you can see, Numpy allows only one type.


In [14]:
np.array([3.14 , 8 ,9, 10,4], dtype="int")

array([ 3,  8,  9, 10,  4])

We can make adjustments.

## Sıfırdan array oluşturma.


In [15]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones((3,5), dtype=int) #three rows five columns. Create a two-dimensional array.

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.full((3,4),3) #To create from a fixed number.

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [20]:
np.arange(0,58,7) 

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56])

In [21]:
np.linspace(0,1, 9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [24]:
np.random.normal(10,4,(3,4)) # 10=average 4 =standard deviation

array([[17.41738202,  6.51492851,  9.74203356,  5.94610159],
       [ 6.39063777, 15.36846569, 10.1982801 ,  7.69092118],
       [18.93937812, 11.27724679, 14.05987623,  9.26597468]])

In [23]:
np.random.randint(0,10,(4,4))

array([[5, 7, 2, 1],
       [0, 1, 3, 3],
       [9, 1, 8, 5],
       [2, 9, 3, 7]])