# Yeniden şekillendirme( reshaping)

In [1]:
import numpy as np


In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Bunu ifadeyi görüldüğü gibi 3 e 3 matris olarak yeniden şekillendirdik.

In [8]:
a=np.arange(1,10)

In [9]:
a.ndim

1

In [10]:
b=np.arange(1,10).reshape(1,9)

In [11]:
b.ndim

2

In [12]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Görüldüğü gibi iki tane kapalı parantez va bu artık bir matristir.